services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: ros2-adaptive-assembly:jazzy-dev
    container_name: ros2_adaptive_assembly_dev
    working_dir: /workspaces/ros2_adaptive_assembly_ws
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - RCUTILS_COLORIZED_OUTPUT=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ..:/workspaces/ros2_adaptive_assembly_ws/src/ros2_adaptive_assembly:rw
      - ros2_adaptive_assembly_build:/workspaces/ros2_adaptive_assembly_ws/build
      - ros2_adaptive_assembly_install:/workspaces/ros2_adaptive_assembly_ws/install
      - ros2_adaptive_assembly_log:/workspaces/ros2_adaptive_assembly_ws/log
    command: bash -lc "sleep infinity"

volumes:
  ros2_adaptive_assembly_build:
  ros2_adaptive_assembly_install:
  ros2_adaptive_assembly_log:
