fake_object_pose_node:
  ros__parameters:
    publish_period_sec: 5.0
    x_min: 0.442
    x_max: 0.442
    y_min: 0.148
    y_max: 0.148
    z: 0.15
    random_seed: 42
    frame_id: world
    target_frame_id: target_object
    yaw_min: 0.0
    yaw_max: 0.0
    publish_immediately: true

assembly_task_node:
  ros__parameters:
    pre_grasp_height_offset: 0.20
    assembly_height_offset: 0.05
    replan_distance_threshold: 0.03
