#!/usr/bin/env python3
"""Summarize planning diagnostic CSV files."""

import argparse
import csv
from pathlib import Path
import statistics
import sys
from typing import Iterable, List


REQUIRED_COLUMNS = {
    'event',
    'duration_ms',
}
EVENT_SUCCESS = 'success'
EVENT_FAILURE = 'failure'
EVENT_SKIPPED = 'skipped_small_motion'


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Summarize planning diagnostics CSV metrics.'
    )
    parser.add_argument(
        '--input',
        required=True,
        help='Input CSV generated by record_planning_diagnostics_csv.py.',
    )
    return parser.parse_args()


def _read_rows(input_path: Path) -> List[dict]:
    if not input_path.exists():
        raise RuntimeError(f'input CSV does not exist: {input_path}')

    with input_path.open(newline='', encoding='utf-8') as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None:
            raise RuntimeError('input CSV is empty or missing a header')

        missing_columns = sorted(REQUIRED_COLUMNS - set(reader.fieldnames))
        if missing_columns:
            raise RuntimeError(
                'input CSV is missing required column(s): '
                + ', '.join(missing_columns)
            )

        rows = list(reader)

    if not rows:
        raise RuntimeError('input CSV contains no planning events')
    return rows


def _duration_values(rows: Iterable[dict]) -> List[float]:
    durations = []
    for row in rows:
        event = row.get('event', '')
        if event not in {EVENT_SUCCESS, EVENT_FAILURE}:
            continue
        try:
            durations.append(float(row.get('duration_ms', '')))
        except ValueError as error:
            raise RuntimeError(
                f'invalid duration_ms for event={event}: '
                f'{row.get("duration_ms", "")}'
            ) from error
    return durations


def _format_fraction(numerator: int, denominator: int) -> str:
    if denominator == 0:
        return 'n/a'
    return f'{numerator / denominator:.3f}'


def _format_duration(value: float) -> str:
    return f'{value:.3f} ms'


def _print_summary(rows: List[dict]) -> None:
    total_events = len(rows)
    success_count = sum(1 for row in rows if row.get('event') == EVENT_SUCCESS)
    failure_count = sum(1 for row in rows if row.get('event') == EVENT_FAILURE)
    skipped_count = sum(1 for row in rows if row.get('event') == EVENT_SKIPPED)
    planning_attempts = success_count + failure_count
    durations = _duration_values(rows)

    print('Planning diagnostics summary')
    print('----------------------------')
    print(f'total events: {total_events}')
    print(f'success: {success_count}')
    print(f'failure: {failure_count}')
    print(f'skipped_small_motion: {skipped_count}')
    print(f'planning attempts: {planning_attempts}')
    print(
        'planning success rate over attempts: '
        f'{_format_fraction(success_count, planning_attempts)}'
    )
    print(
        'overall success fraction over all events: '
        f'{_format_fraction(success_count, total_events)}'
    )

    if durations:
        print(
            'average duration_ms over planning attempts: '
            f'{_format_duration(statistics.mean(durations))}'
        )
        print(
            'median duration_ms over planning attempts: '
            f'{_format_duration(statistics.median(durations))}'
        )
        print(
            'min duration_ms over planning attempts: '
            f'{_format_duration(min(durations))}'
        )
        print(
            'max duration_ms over planning attempts: '
            f'{_format_duration(max(durations))}'
        )
    else:
        print('average duration_ms over planning attempts: n/a')
        print('median duration_ms over planning attempts: n/a')
        print('min duration_ms over planning attempts: n/a')
        print('max duration_ms over planning attempts: n/a')


def main() -> int:
    """Summarize an input planning diagnostics CSV."""
    args = _parse_args()
    try:
        rows = _read_rows(Path(args.input))
        _print_summary(rows)
    except RuntimeError as error:
        print(f'FAIL: {error}')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
