#!/usr/bin/env python3
"""Summarize contact-lite insertion benchmark CSV files."""

import argparse
import csv
from pathlib import Path
import statistics
import sys
from typing import List


REQUIRED_COLUMNS = {
    'success',
    'position_error_mm',
    'orientation_error_deg',
    'position_tolerance_mm',
    'orientation_tolerance_deg',
    'execution_required',
    'execution_success',
    'achieved_pose_source',
}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Summarize contact-lite insertion benchmark CSV metrics.'
    )
    parser.add_argument(
        '--input',
        required=True,
        help='Input CSV generated by record_contact_lite_insertion_csv.py.',
    )
    parser.add_argument(
        '--output-markdown',
        help='Optional Markdown summary output path.',
    )
    return parser.parse_args()


def _read_rows(input_path: Path) -> List[dict]:
    if not input_path.exists():
        raise RuntimeError(f'input CSV does not exist: {input_path}')

    with input_path.open(newline='', encoding='utf-8') as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None:
            raise RuntimeError('input CSV is empty or missing a header')
        missing_columns = sorted(REQUIRED_COLUMNS - set(reader.fieldnames))
        if missing_columns:
            raise RuntimeError(
                'input CSV is missing required column(s): '
                + ', '.join(missing_columns)
            )
        rows = list(reader)

    if not rows:
        raise RuntimeError('input CSV contains no insertion trials')
    return rows


def _float_values(rows: List[dict], column: str) -> List[float]:
    values = []
    for row in rows:
        try:
            values.append(float(row.get(column, '')))
        except ValueError as error:
            raise RuntimeError(
                f'invalid {column}: {row.get(column, "")}'
            ) from error
    return values


def _unique_nonempty(rows: List[dict], column: str) -> str:
    values = sorted({
        row.get(column, '') for row in rows
        if row.get(column, '')
    })
    return ', '.join(values) if values else 'n/a'


def _summary_lines(rows: List[dict]) -> List[str]:
    total_trials = len(rows)
    success_count = sum(1 for row in rows if row.get('success') == 'true')
    failure_count = total_trials - success_count
    position_errors = _float_values(rows, 'position_error_mm')
    orientation_errors = _float_values(rows, 'orientation_error_deg')
    success_rate = success_count / total_trials

    return [
        'Contact-lite insertion benchmark summary',
        '----------------------------------------',
        f'total trials: {total_trials}',
        f'success count: {success_count}',
        f'failure count: {failure_count}',
        f'success rate: {success_rate:.3f}',
        f'mean position error: {statistics.mean(position_errors):.6f} mm',
        f'max position error: {max(position_errors):.6f} mm',
        'mean orientation error: '
        f'{statistics.mean(orientation_errors):.6f} deg',
        f'max orientation error: {max(orientation_errors):.6f} deg',
        'position tolerance settings: '
        f'{_unique_nonempty(rows, "position_tolerance_mm")} mm',
        'orientation tolerance settings: '
        f'{_unique_nonempty(rows, "orientation_tolerance_deg")} deg',
        f'execution required: {_unique_nonempty(rows, "execution_required")}',
        f'execution success: {_unique_nonempty(rows, "execution_success")}',
        'achieved pose source: '
        f'{_unique_nonempty(rows, "achieved_pose_source")}',
        'known limitation: contact-lite geometric benchmark only, not '
        'force/contact-rich insertion.',
    ]


def _markdown_summary(rows: List[dict]) -> str:
    total_trials = len(rows)
    success_count = sum(1 for row in rows if row.get('success') == 'true')
    failure_count = total_trials - success_count
    position_errors = _float_values(rows, 'position_error_mm')
    orientation_errors = _float_values(rows, 'orientation_error_deg')
    success_rate = success_count / total_trials
    return '\n'.join([
        '# Contact-lite Insertion Benchmark Summary',
        '',
        f'- total trials: {total_trials}',
        f'- success count: {success_count}',
        f'- failure count: {failure_count}',
        f'- success rate: {success_rate:.3f}',
        f'- mean position error: {statistics.mean(position_errors):.6f} mm',
        f'- max position error: {max(position_errors):.6f} mm',
        '- mean orientation error: '
        f'{statistics.mean(orientation_errors):.6f} deg',
        f'- max orientation error: {max(orientation_errors):.6f} deg',
        '- position tolerance settings: '
        f'{_unique_nonempty(rows, "position_tolerance_mm")} mm',
        '- orientation tolerance settings: '
        f'{_unique_nonempty(rows, "orientation_tolerance_deg")} deg',
        '- execution required: '
        f'{_unique_nonempty(rows, "execution_required")}',
        f'- execution success: {_unique_nonempty(rows, "execution_success")}',
        '- achieved pose source: '
        f'{_unique_nonempty(rows, "achieved_pose_source")}',
        '',
        'Known limitation: contact-lite geometric benchmark only, not '
        'force/contact-rich insertion.',
        '',
    ])


def main() -> int:
    """Summarize an input insertion benchmark CSV."""
    args = _parse_args()
    try:
        rows = _read_rows(Path(args.input))
        print('\n'.join(_summary_lines(rows)))
        if args.output_markdown:
            output_path = Path(args.output_markdown)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(_markdown_summary(rows), encoding='utf-8')
            print(f'Wrote Markdown summary: {output_path}')
    except RuntimeError as error:
        print(f'FAIL: {error}')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
